version: "3.2"
services:
  zookeeper:
    image: zookeeper:3.4.10
    container_name: zoo
    ports:
      - "2181:2181"
    volumes:
      - zoo-data:/var/lib/zookeeper/data
      - zoo-log:/var/lib/zookeeper/log
    networks:
      - kafka

  kafka1:
    image: rookiefly/kafka:latest
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka
    depends_on:
      - zookeeper

  kafka-center:
    container_name: KafkaCenter
    image: xaecbd/kafka-center:2.3.0
    ports:
      - "8080:8080"
    volumes:
      - ./application.properties:/opt/app/kafka-center/config/application.properties
    networks:
      - kafka
    depends_on:
      - mysqldb
      - elasticsearch
      - zookeeper
      - kafka1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - eslogs01:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
    networks:
      - kafka

  mysqldb:
    image: rookiefly/mysql:latest
    container_name: mysqldb
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kafka_center
    ports:
      - "3306:3306"
    networks:
      - kafka

volumes:
  eslogs01:
    driver: local
  esdata01:
    driver: local
  mysql-data:
    driver: local
  zoo-data:
    driver: local
  zoo-log:
    driver: local
networks:
  kafka:
    driver: bridge
