version: "3"

services:
  namenode:
    networks:
      - hive
    image: rookiefly/hadoop-namenode:2.10.1
    # volumes:
    #   - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"

  datanode:
    networks:
      - hive
    image: rookiefly/hadoop-datanode:2.10.1
    # volumes:
    #   - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"

  hive-server:
    networks:
      - hive
    image: rookiefly/hive:2.3.7
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"

  hive-metastore:
    networks:
      - hive
    image: rookiefly/hive:2.3.7
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"

  hive-metastore-postgresql:
    networks:
      - hive
    image: rookiefly/hive-metastore-postgresql:2.3.0

  hue:
    networks:
      - hive
    image: gethue/hue:latest
    ports:
      - "8888:8888"
      
  mysqldb:
    networks:
      - hive
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  zoo:
    image: zookeeper:3.4.10
    networks:
      - hive
    container_name: zoo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - 2181:2181

  hbase-master:
    image: rookiefly/hbase-master:2.3.3
    networks:
      - hive
    container_name: hbase-master
    hostname: hbase-master
    env_file:
      - ./hbase-distributed-local.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zoo:2181"
    ports:
      - 16010:16010

  hbase-region:
    image: rookiefly/hbase-regionserver:2.3.3
    networks:
      - hive
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    env_file:
      - ./hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zoo:2181 hbase-master:16010"
    ports:
      - 16030:16030
networks:
  hive:
    name: hive
    driver: bridge
