version: "3.2"

services:
  namenode:
    hostname: namenode
    networks:
      - hive
    image: rookiefly/hadoop-namenode:2.10.1
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
    deploy:
      replicas: 1

  datanode:
    hostname: datanode
    networks:
      - hive
    image: rookiefly/hadoop-datanode:2.10.1
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"
    depends_on:
      - "namenode"
    deploy:
      replicas: 1

  hive-server:
    hostname: hive-server
    networks:
      - hive
    image: rookiefly/hive:2.3.7
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    depends_on:
      - "hive-metastore"
    deploy:
      replicas: 1

  hive-metastore:
    hostname: hive-metastore
    networks:
      - hive
    image: rookiefly/hive:2.3.7
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    depends_on:
      - "hive-metastore-postgresql"
      - "namenode"
      - "datanode"
    deploy:
      replicas: 1

  hive-metastore-postgresql:
    hostname: hive-metastore-postgresql
    networks:
      - hive
    image: rookiefly/hive-metastore-postgresql:2.3.0
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  hue:
    image: rookiefly/hue:latest
    hostname: hue
    networks:
      - hive
    ports:
      - "8888:8888"
    # volumes:
    #   - ./hue.ini:/usr/share/hue/desktop/conf/hue.ini
    depends_on:
      - "mysqldb"
    deploy:
      replicas: 1

  mysqldb:
    image: mysql:5.7
    hostname: mysqldb
    networks:
      - hive
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - mysqldb_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hue
      MYSQL_USER: hue
      MYSQL_PASSWORD: hue
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  zoo:
    image: zookeeper:3.4.10
    networks:
      - hive
    hostname: zoo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    ports:
      - 2181:2181
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  hbase-master:
    image: rookiefly/hbase-master:2.3.3
    networks:
      - hive
    hostname: hbase-master
    env_file:
      - ./hbase-distributed-local.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zoo:2181"
    ports:
      - 16010:16010
    depends_on:
      - "zoo"
      - "namenode"
      - "datanode"
    deploy:
      replicas: 1

  hbase-region:
    image: rookiefly/hbase-regionserver:2.3.3
    networks:
      - hive
    hostname: hbase-regionserver
    env_file:
      - ./hbase-distributed-local.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zoo:2181 hbase-master:16010"
    ports:
      - 16030:16030
    depends_on:
      - "zoo"
      - "namenode"
      - "datanode"
      - "hbase-master"
    deploy:
      replicas: 1

networks:
  hive:
    driver: overlay

volumes:
  hadoop_namenode:
  hadoop_datanode:
  mysqldb_data: