version: "3.6"

services:
  gitea:
    image: gitea/gitea:1.13.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - APP_NAME=Gitea
      - RUN_MODE=prod
      - RUN_USER=git
      - SSH_DOMAIN=git.rookiefly.com
      - SSH_PORT=0
      - SSH_LISTEN_PORT=0
      - DISABLE_SSH=true
      - HTTP_PORT=3000
      - ROOT_URL=https://git.rookiefly.com
      - DB_TYPE=mysql
      - DB_HOST=giteadb
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - DB_CHARSET=utf8
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.services.giteaweb.loadbalancer.server.scheme=http"
      - "traefik.http.services.giteaweb.loadbalancer.server.port=3000"
      # - "traefik.tcp.routers.giteassh.rule=HostSNI(`*`)"
      # - "traefik.tcp.routers.giteassh.tls=true"
      # - "traefik.tcp.routers.giteassh.entrypoints=ssh"
      # - "traefik.tcp.routers.giteassh.service=gitea"
      # - "traefik.tcp.services.gitea.loadbalancer.server.port=22"
    networks:
      - traefik_default
      - gitea
    expose:
      - 3000
      # - 22
    restart: unless-stopped
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
      - ./repositories:/data/git/repositories
      - ./data:/data/gitea/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    extra_hosts:
      - "git.rookiefly.com:127.0.0.1"
    # healthcheck:
    #   test:
    #     ["CMD-SHELL", "wget -q --spider --proxy off localhost:3000 || exit 1"]
    #   interval: 5s

  giteadb:
    image: mysql:5.7
    container_name: gitea_db
    restart: always
    networks:
      - gitea
    expose:
      - 3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: gitea
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: gitea
      TZ: Asia/Shanghai
    volumes:
      - ./mysql:/var/lib/mysql
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
    # healthcheck:
    #   test: ["CMD-SHELL", "/etc/init.d/mysql status"]
    #   interval: 30s

networks:
  gitea:
    internal: true
  traefik_default:
    external: true
