version: "3.5"

services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 2222:22
    volumes:
      - "./certs:/etc/certs/"
      - "./logs/:/var/logs/access.log"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config:/etc/traefik"
