http:
  routers:
    api:
      entryPoints:
        - "web"
      rule: "Host(`traefik.rookiefly.com`)"
      service: api@internal
      middlewares:
        - http-redirect
    api-tls:
      entryPoints:
        - "websecure"
      rule: "Host(`traefik.rookiefly.com`)"
      service: api@internal
      tls: {}
      middlewares:
        - http-auth
        - http-compress
    metrics:
      entryPoints:
        - "websecure"
      rule: "Host(`traefik.rookiefly.com`) && Path(`/metrics`)"
      service: prometheus@internal
      tls: {}
      middlewares:
        - http-compress
    whoami:
      entryPoints:
        - "websecure"
      rule: "Host(`traefik.rookiefly.com`) && Path(`/whoami`)"
      service: whoami-traefik@docker
      tls: {}
      middlewares:
        - http-compress
    giteaweb:
      entryPoints:
        - "websecure"
      rule: "Host(`git.rookiefly.com`)"
      service: giteaweb@docker
      tls: {}
      middlewares:
        - http-compress
    harbor:
      entryPoints:
        - "websecure"
      rule: "Host(`hub.rookiefly.com`)"
      service: proxy-harbor@docker
      tls: {}
      middlewares:
        - http-compress
  middlewares:
    http-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    http-auth:
      basicAuth:
        users:
          - "test:$apr1$k.xiBHjv$VdavfNvly69vNZvkKpB2j0"
    http-compress:
      compress: {}
    # ghost:
    #   entryPoints:
    #     - "websecure"
    #   rule: "Host(`ghost.rookiefly.com`) "
    #   service: ghost
    #   tls: true
  # services:
  #   ghost:
  #     loadBalancer:
  #       servers:
  #         - url: "http://127.0.0.1:2368/"
# tcp:
#   routers:
#     giteassh:
#       entryPoints:
#         - "ssh"
#       rule: "HostSNI(`git.rookiefly.com`)"
#       service: giteassh@docker
#       tls: true
