http:
  middlewares:
    httpsRedirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    httpcompress:
      compress: {}
  routers:
    api:
      entryPoints:
        - "websecure"
      rule: "Host(`traefik.rookiefly.com`)"
      service: api@internal
      tls: true
    metrics:
      entryPoints:
        - "websecure"
      rule: "Host(`traefik.rookiefly.com`) && Path(`/metrics`)"
      service: prometheus@internal
      tls: true
    whoami:
      entryPoints:
        - "websecure"
      rule: "Host(`traefik.rookiefly.com`) && Path(`/whoami`)"
      service: whoami-traefik@docker
      tls: true
    giteaweb:
      entryPoints:
        - "websecure"
      rule: "Host(`git.rookiefly.com`)"
      service: giteaweb@docker
      tls: true
    harbor:
      entryPoints:
        - "websecure"
      rule: "Host(`hub.rookiefly.com`)"
      service: proxy-harbor@docker
      tls: true
    # ghost:
    #   entryPoints:
    #     - "websecure"
    #   rule: "Host(`ghost.rookiefly.com`) "
    #   service: ghost
    #   tls: true
  # services:
  #   ghost:
  #     loadBalancer:
  #       servers:
  #         - url: "http://127.0.0.1:2368/"
# tcp:
#   routers:
#     giteassh:
#       entryPoints:
#         - "ssh"
#       rule: "HostSNI(`git.rookiefly.com`)"
#       service: giteassh@docker
#       tls: true
