providers:
  docker: {}
  file:
    directory: "/etc/traefik"
    filename: "dynamic.yml"
    watch: true

log:
  level: DEBUG

accessLog:
  filePath: "/var/logs/access.log"
  bufferingSize: 100

metrics:
  prometheus:
    entryPoint: metrics

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/fullchain.pem
        keyFile: /etc/certs/privkey.pem
  certificates:
    - certFile: /etc/certs/fullchain.pem
      keyFile: /etc/certs/privkey.pem

api:
  dashboard: true
