providers:
  docker: {}
  file:
    directory: "/etc/traefik"
    filename: "dynamic.yml"
    watch: true

log:
  level: DEBUG
  filePath: "/logdata/traefik.log"
# accessLog:
#   filePath: "/logdata/access.log"

metrics:
  prometheus: {}

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  ssh:
    address: ":2222"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/fullchain.pem
        keyFile: /etc/certs/privkey.pem
  certificates:
    - certFile: /etc/certs/fullchain.pem
      keyFile: /etc/certs/privkey.pem

api:
  dashboard: true
